#!/bin/bash

cmake -DBUILD_BSATOOL=OFF -DBUILD_ESMTOOL=OFF -DBUILD_LAUNCHER=OFF -DBUILD_MWINIIMPORTER=OFF -DBUILD_ESSIMPORTER=OFF -DBUILD_OPENCS=OFF -DBUILD_WIZARD=OFF -DBUILD_WITH_CODE_COVERAGE=OFF -DBUILD_UNITTESTS=OFF -DBUILD_NIFTEST=OFF -DBUILD_MYGUI_PLUGIN=OFF -DBUILD_DOCS=OFF ..
