#ifndef MGCOMPAT_HPP_
#define MGCOMPAT_HPP_

#include <map>
#include <SDL_events.h>
#include "MyGUI_KeyCode.h"

namespace SDLUtil
{

static std::map<SDL_Keycode, MyGUI::KeyCode::Enum> mgmap_tab = {
    { SDLK_UNKNOWN, MyGUI::KeyCode::None },
    { SDLK_ESCAPE, MyGUI::KeyCode::Escape },
    { SDLK_1, MyGUI::KeyCode::One },
    { SDLK_2, MyGUI::KeyCode::Two },
    { SDLK_3, MyGUI::KeyCode::Three },
    { SDLK_4, MyGUI::KeyCode::Four },
    { SDLK_5, MyGUI::KeyCode::Five },
    { SDLK_6, MyGUI::KeyCode::Six },
    { SDLK_7, MyGUI::KeyCode::Seven },
    { SDLK_8, MyGUI::KeyCode::Eight },
    { SDLK_9, MyGUI::KeyCode::Nine },
    { SDLK_0, MyGUI::KeyCode::Zero },
    { SDLK_MINUS, MyGUI::KeyCode::Minus },
    { SDLK_EQUALS, MyGUI::KeyCode::Equals },
    { SDLK_BACKSPACE, MyGUI::KeyCode::Backspace },
    { SDLK_TAB, MyGUI::KeyCode::Tab },
    { SDLK_q, MyGUI::KeyCode::Q },
    { SDLK_w, MyGUI::KeyCode::W },
    { SDLK_e, MyGUI::KeyCode::E },
    { SDLK_r, MyGUI::KeyCode::R },
    { SDLK_t, MyGUI::KeyCode::T },
    { SDLK_y, MyGUI::KeyCode::Y },
    { SDLK_u, MyGUI::KeyCode::U },
    { SDLK_i, MyGUI::KeyCode::I },
    { SDLK_o, MyGUI::KeyCode::O },
    { SDLK_p, MyGUI::KeyCode::P },
    { SDLK_RETURN, MyGUI::KeyCode::Return },
    { SDLK_a, MyGUI::KeyCode::A },
    { SDLK_s, MyGUI::KeyCode::S },
    { SDLK_d, MyGUI::KeyCode::D },
    { SDLK_f, MyGUI::KeyCode::F },
    { SDLK_g, MyGUI::KeyCode::G },
    { SDLK_h, MyGUI::KeyCode::H },
    { SDLK_j, MyGUI::KeyCode::J },
    { SDLK_k, MyGUI::KeyCode::K },
    { SDLK_l, MyGUI::KeyCode::L },
    { SDLK_SEMICOLON, MyGUI::KeyCode::Semicolon },
    { SDLK_COLON, MyGUI::KeyCode::Colon },
    { SDLK_QUOTE, MyGUI::KeyCode::Apostrophe },
    { SDLK_BACKQUOTE, MyGUI::KeyCode::Grave },
    { SDLK_LSHIFT, MyGUI::KeyCode::LeftShift },
    { SDLK_BACKSLASH, MyGUI::KeyCode::Backslash },
    { SDLK_SLASH, MyGUI::KeyCode::Slash },
    { SDLK_z, MyGUI::KeyCode::Z },
    { SDLK_x, MyGUI::KeyCode::X },
    { SDLK_c, MyGUI::KeyCode::C },
    { SDLK_v, MyGUI::KeyCode::V },
    { SDLK_b, MyGUI::KeyCode::B },
    { SDLK_n, MyGUI::KeyCode::N },
    { SDLK_m, MyGUI::KeyCode::M },
    { SDLK_COMMA, MyGUI::KeyCode::Comma },
    { SDLK_PERIOD, MyGUI::KeyCode::Period },
    { SDLK_RSHIFT, MyGUI::KeyCode::RightShift },
    { SDLK_KP_MULTIPLY, MyGUI::KeyCode::Multiply },
    { SDLK_LALT, MyGUI::KeyCode::LeftAlt },
    { SDLK_SPACE, MyGUI::KeyCode::Space },
    { SDLK_CAPSLOCK, MyGUI::KeyCode::Capital },
    { SDLK_F1, MyGUI::KeyCode::F1 },
    { SDLK_F2, MyGUI::KeyCode::F2 },
    { SDLK_F3, MyGUI::KeyCode::F3 },
    { SDLK_F4, MyGUI::KeyCode::F4 },
    { SDLK_F5, MyGUI::KeyCode::F5 },
    { SDLK_F6, MyGUI::KeyCode::F6 },
    { SDLK_F7, MyGUI::KeyCode::F7 },
    { SDLK_F8, MyGUI::KeyCode::F8 },
    { SDLK_F9, MyGUI::KeyCode::F9 },
    { SDLK_F10, MyGUI::KeyCode::F10 },
    { SDLK_NUMLOCKCLEAR, MyGUI::KeyCode::NumLock },
    { SDLK_SCROLLLOCK, MyGUI::KeyCode::ScrollLock },
    { SDLK_KP_7, MyGUI::KeyCode::Numpad7 },
    { SDLK_KP_8, MyGUI::KeyCode::Numpad8 },
    { SDLK_KP_9, MyGUI::KeyCode::Numpad9 },
    { SDLK_KP_MINUS, MyGUI::KeyCode::Subtract },
    { SDLK_KP_4, MyGUI::KeyCode::Numpad4 },
    { SDLK_KP_5, MyGUI::KeyCode::Numpad5 },
    { SDLK_KP_6, MyGUI::KeyCode::Numpad6 },
    { SDLK_KP_PLUS, MyGUI::KeyCode::Add },
    { SDLK_KP_1, MyGUI::KeyCode::Numpad1 },
    { SDLK_KP_2, MyGUI::KeyCode::Numpad2 },
    { SDLK_KP_3, MyGUI::KeyCode::Numpad3 },
    { SDLK_KP_0, MyGUI::KeyCode::Numpad0 },
    { SDLK_KP_PERIOD, MyGUI::KeyCode::Decimal },
    { SDLK_F11, MyGUI::KeyCode::F11 },
    { SDLK_F12, MyGUI::KeyCode::F12 },
    { SDLK_F13, MyGUI::KeyCode::F13 },
    { SDLK_F14, MyGUI::KeyCode::F14 },
    { SDLK_F15, MyGUI::KeyCode::F15 },
    { SDLK_KP_EQUALS, MyGUI::KeyCode::NumpadEquals },
    { SDLK_KP_DIVIDE, MyGUI::KeyCode::Divide },
    { SDLK_SYSREQ, MyGUI::KeyCode::SysRq },
    { SDLK_RALT, MyGUI::KeyCode::RightAlt },
    { SDLK_HOME, MyGUI::KeyCode::Home },
    { SDLK_UP, MyGUI::KeyCode::ArrowUp },
    { SDLK_PAGEUP, MyGUI::KeyCode::PageUp },
    { SDLK_LEFT, MyGUI::KeyCode::ArrowLeft },
    { SDLK_RIGHT, MyGUI::KeyCode::ArrowRight },
    { SDLK_END, MyGUI::KeyCode::End },
    { SDLK_DOWN, MyGUI::KeyCode::ArrowDown },
    { SDLK_PAGEDOWN, MyGUI::KeyCode::PageDown },
    { SDLK_INSERT, MyGUI::KeyCode::Insert },
    { SDLK_DELETE, MyGUI::KeyCode::Delete },
    { SDLK_KP_ENTER, MyGUI::KeyCode::NumpadEnter },
    { SDLK_APPLICATION, MyGUI::KeyCode::AppMenu },
    { SDLK_LGUI, MyGUI::KeyCode::LeftWindows },
    { SDLK_RGUI, MyGUI::KeyCode::RightWindows },
    { SDLK_LCTRL, MyGUI::KeyCode::LeftControl },
    { SDLK_RCTRL, MyGUI::KeyCode::RightControl }
};

}

#endif /* MGCOMPAT_HPP_ */
